### PR TITLE
Update tools.json - Adjustments to the TwinCAT entry

### PR DESCRIPTION
**Pull request by Tc-KGu**
Adjustments to the TwinCAT entry

### CODE REVIEW

**Review by chrbertsch — CHANGES_REQUESTED** [review]
https://github.com/Beckhoff/TE142x---FMU-Samples
is not accessible, I get a "404" error

**Comment by Tc-KGu** [comment]
Thanks for the hint, unfortunately I can't change the visibility of the repo, one of the admins will do that tomorrow

**Comment by Tc-KGu** [comment]
done, the repo ist now public!

**Review by chrbertsch — CHANGES_REQUESTED** [review]
Thanks for providing the examples!
Could you please add a README.md describing with which validation tools from https://fmi-standard.org/validation/ and with which other FMU importing tools you have tested these FMUs? And perhaps add reference results as csv?
And add also for the FMU import: with which FMUs have you tested it (Reference FMUs, FMUs from other FMU exporting tools)?

**Pull request merged**
