### PR TITLE
Add VI-CarRealTime to the tools list

### PR DESCRIPTION
**Pull request by paolo-vigrade**
Add VI-CarRealTime from VI-grade, together with the company logo, in the toos list. VI-CarRealTime is a tool for vehicle dynamics engineering.

### CODE REVIEW

**Review by chrbertsch — COMMENTED** [review]
For the examplesURL you are encouraged to provide a link to a webpage or repo where you document how you tested your tool w.r.t to FMI support. See e.g. [https://github.com/altairengineering/fmus](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faltairengineering%2Ffmus&data=05%7C01%7CChristian.Bertsch%40de.bosch.com%7C01cb7050c3044b3d2c2e08dbd1ac4020%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C638334309952318885%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7cblzvmoxG496WskCZUVcxnJzQU8aDUxkUDtydXdl2A%3D&reserved=0) for an example and the first four tools listed on https://fmi-standard.org/tools/ for examples

**Comment by paolo-vigrade** [comment]
Thank you for the suggestion. At the moment we have not collected any public material about the executed testing, but I highlight this to our product development team.

**Review by chrbertsch — APPROVED** [review]
You can add the "compatibility information" also in a separate pull request.

**Comment by paolo-vigrade** [comment]
Thank you.

**Pull request merged**
