### PR TITLE
Update website after FMI3.0 release

### PR DESCRIPTION
**Pull request by chrbertsch**
[x] Update FAQ with features
[x] create news item
[x] Update download buttons for spec
[x] Add news item on approval by MA
[x] Add news item "Press release"

### CODE REVIEW

**Review by andreas-junghanns — CHANGES_REQUESTED** [review]
Press release text must be copied in

**Comment by andreas-junghanns** [comment]
- /tools page must also have a reference to FMI 3.0 - maybe not with proper XC data, but at least a disclaimer that 3.0 will be added soon.

**Comment by andreas-junghanns** [comment]
* /assets must have the 3.0 zip package copied into

**Comment by chrbertsch** [comment]
@t-sommer , @andreas-junghanns , @hubertus65 : We should prepare this on Monday, so that we can review it to be ready after the release

**Review by andreas-junghanns — APPROVED** [review]

**Review by andreas-junghanns — APPROVED** [review]

**Comment by chrbertsch** [comment]
@t-sommer : Shall we provide the released html version of the standard at  https://fmi-standard.org/docs/3.0  and use https://fmi-standard.org/docs/3.0-dev/ for further development of FMI 3.1, while we create a branch https://github.com/modelica/fmi-standard/tree/support/v3.0.x for maintenance?

**Comment by t-sommer** [comment]
👍

**Review by andreas-junghanns — APPROVED** [review]

**Pull request merged**
