### PR TITLE
Add three paragraph summary to front page

### LINKED ISSUE #430: "FMI in a nutshell" for FMI website
motivated by "Julia in a Nutshell" on  https://julialang.org/: 
I suggest to create a "FMI in a Nutshell" description with a similar formatting: 

First draft (brain-storming): 

**Containerized models**
The tool-independent FMI standard describes the interface of models (inputs, outputs and parameters) in an XML file, and provides an API how to interact with the model with different interface types depending on the inclusion of a solver or scheduler
**Enabling collaboration**
FMI enables collaborative model-based engineering through the exchange of black-box models, hiding internal model and thus enabling protection of intellectual properties
**Portable**
FMI supports many platforms, and via source code representation and a build-configuration, porting to many  platforms is easy, including PC, HiL-Systems, Cloud. 
**Multi-Domain**
FMI can encapsulate a large range of model, from physics-based dynamical models over machine Learning and AI models to virtual electronic control systems (ECUs)
**Open-source and free**
The FMI standard text and headers are a available under an open source licenses an free to useDe-Facto Industry Standard
FMI is supported by more than 170 simulation tools
**De-facto Industry Standard**
FMI is supported by more than 170 modelling and simulation tools. It is developed by a community companies and organizations and the umbrella of the Modelica Association.

(In more detail, FMI shall be described in a whitepaper which shall also be linked on the FMI website, https://github.com/modelica/fmi-design/issues/23)

Please comment.

### PR DESCRIPTION
**Pull request by t-sommer**
fixes #430

### CODE REVIEW

**Review by chrbertsch — CHANGES_REQUESTED** [review]
The current proposal describes properties of FMI ("free, open-source ..."), but I am missing a description of the core of _what FMI is_, as the previously present text "`The Functional Mock-up Interface is a free standard that defines a container and an interface to exchange dynamic models using a combination of XML files, binaries and C code zipped into a single file`." gets removed.
Additionally, we could write something about the benefit of using FMI, e.g. "enabling collaboration" from https://github.com/modelica/fmi-standard.org/issues/430

**Review by andreas-junghanns — CHANGES_REQUESTED** [review]
I was never fond of absolutes in self-praise: "The leading standard..." - measured how? I am sure there are also a lot of S-Functions out there.
Maybe a bit more modest would be "A leading standard..."?

**Comment by chrbertsch** [comment]
> I was never fond of absolutes in self-praise: "The leading standard..." - measured how? I am sure there are also a lot of S-Functions out there. Maybe a bit more modest would be "A leading standard..."?

What about: 
"The de facto industry standard for tool-independent exchange and co-simulation of dynamical simulation models."

**Comment by andreas-junghanns** [comment]
This is a sentence that we have used often. It is a bit long,  but we never new how to shorten it without loosing important information - and FMI does quite a bit, so a long sentence is probably ok.
But is that better than what we have now? What was the original intend of the change?

**Comment by t-sommer** [comment]
The idea is to make FMI more "approachable" for people that had not prior contact with the standard. I personally think we should try to convey the general idea instead of putting technical details in the headline.

**Comment by t-sommer** [comment]
Decision after call with @chrbertsch and @andreas-junghanns: merge now and improve incrementally, if necessary.

**Pull request merged**
