### PR TITLE
Update logo

### PR DESCRIPTION
**Pull request by chrbertsch**
Update to new logo according to https://github.com/modelica/fmi-standard.org/issues/217

@t-sommer and @andreas-junghanns  : please check carefully, website has not yet been tested locally.

### CODE REVIEW

**Comment by andreas-junghanns** [comment]
The post does not seem to make it - not sure why, it is also missing in the bigger new page.
The changes in the image are ok.
Where can I check the usage of favicons?

**Comment by andreas-junghanns** [comment]
> 
> 
> The post does not seem to make it - not sure why, it is also missing in the bigger new page.
> The changes in the image are ok.
> Where can I check the usage of favicons?

Ah, found an error message from jekyll: Skipping:
"_posts/2020-03-30-new-fmi-logo.md has a future date"

How so?

**Comment by chrbertsch** [comment]
> Where can I check the usage of favicons?

They are used in the tabs if my browser
grafik

**Comment by andreas-junghanns** [comment]
> They are used in the tabs if my browser
> grafik

Does not work (checked with firefox and iexplorer). I get two different icons that look like defaults (world and i).

**Comment by t-sommer** [comment]
Superseded by #242

**Pull request closed without merging**
