### PR TITLE
Re-structure and clean up

### PR DESCRIPTION
**Pull request by t-sommer**
- add bottom navbar
- add "Privacy" page and link to bottom navbar
- move "FAQ" and "Contact" links to bottom navbar
- add posts layout
- clean up post file names, headlines and front matters
- show only news headline on the start page
- remove obsolete "minima" theme from _config.yml

### CODE REVIEW

**Comment by andreas-junghanns** [comment]
I think I pushed into your branch/PR?! Please check what I did and maybe you can see my suggested changes?

**Comment by t-sommer** [comment]
I've applied your proposed changes

**Comment by t-sommer** [comment]
@chrbertsch, @andreas-junghanns, if you give me a thumbs up, I can squash and merge this PR

**Comment by chrbertsch** [comment]
Looks good to me (have only looked a the diffs, not built the pages locally)

**Comment by andreas-junghanns** [comment]
I am a bit worried that we do all this in one.
I was hoping that we could apply some of the changes in pieces so that we can revert in case of vetoes.
Let's do this for the future, here it seems too late, we have to address vetoes with changes and not reverts.

Go!

**Pull request merged**
