### PR TITLE
Add RF::ViPer

### PR DESCRIPTION
**Pull request by miriamschleipenEKS**
Add RF::ViPer as tool which supports FMI

### CODE REVIEW

**Review by chrbertsch — APPROVED** [review]
Thanks!
I would like to encourage you to provide "Compatibility information" (by providing a a to a Webpage in “examplesURL”, see https://github.com/modelica/fmi-standard.org/blob/main/CONTRIBUTING.md#compatibility-information, can be in a separate pull request) describing how you tested your FMI support; you can take one of the first tools listed on https://fmi-standard.org/tools/ as an example.
Benefit for you: Your users will be confident to use your FMI implementation. Additionally your tool will be listed top and get the “golden star”.

**Comment by chrbertsch** [comment]
The logo is not displayed correctly. @t-sommer , @miriamschleipenEKS : any ideas?
grafik

**Comment by t-sommer** [comment]
Wrong path. I fixed it.

**Comment by miriamschleipenEKS** [comment]
> Wrong path. I fixed it.

Thank you. We took it from the documentation on the homepage.

**Comment by miriamschleipenEKS** [comment]
> Thanks! I would like to encourage you to provide "Compatibility information" (by providing a a to a Webpage in “examplesURL”, see https://github.com/modelica/fmi-standard.org/blob/main/CONTRIBUTING.md#compatibility-information, can be in a separate pull request) describing how you tested your FMI support; you can take one of the first tools listed on https://fmi-standard.org/tools/ as an example. Benefit for you: Your users will be confident to use your FMI implementation. Additionally your tool will be listed top and get the “golden star”.

Thank you, we will consider to update the information accordingly! Already passed it to our product team.

**Pull request merged**
