### PR TITLE
Add Siemens quote to start page

### PR DESCRIPTION
**Pull request by t-sommer**

### CODE REVIEW

**Comment by t-sommer** [comment]
I've condensed the text a little bit to fit the layout. This is what it would look like:

Screenshot 2019-07-26 09 13 57

**Comment by t-sommer** [comment]
@chrbertsch, can you check with Siemens if this is okay?

**Comment by SchenkTim** [comment]
Text change:
"Supported by Siemens from the beginning, FMI is becoming an important building block ..."

Regarding the use of the official logo, iIam still in clarification and let you know any progress on that.

**Comment by RealCosmo** [comment]
Finally clarified everything. So here is the full text and two Siemens logos (one with white layer, one without):
"Supported by Siemens from the beginning, FMI is becoming an important building block in the efficient creation of interdisciplinary, multi-level digital twins of our entire portfolio - from rail and gas turbine engineering to virtual commissioning in the process industry and operational support in manufacturing plants."
- Virginie Maillard, Lead Technology Field Simulation & Digital Twin, [Siemens](https://www.siemens.com)
sie-logo-claim-petrol-rgb
sie-logo-layer-claim-petrol-rgb

**Pull request merged**
