### PR TITLE
Remove PySimulator from tools list

### PR DESCRIPTION
**Pull request by t-sommer**

### CODE REVIEW

**Comment by chrbertsch** [comment]
@tbeu is Pysimulator still maintained?

**Comment by tbeu** [comment]
> @tbeu is Pysimulator still maintained?

Better ask the authors from DLR.

**Comment by chrbertsch** [comment]
@AndreasPfeiffer: Könntest Du bitte kommentieren?

**Comment by AndreasPfeiffer** [comment]
PySimulator will not be maintained.

**Comment by chrbertsch** [comment]
> PySimulator will not be maintained.

Thanks for the reply. Perhaps you could "archive" the Github repo to signal this to the users.

**Review by chrbertsch — APPROVED** [review]

**Pull request merged**
