### PR TITLE
Updated tool information for FMI.jl

### PR DESCRIPTION
**Pull request by ThummeTo**
Updated tool information for FMI.jl

### CODE REVIEW

**Review by chrbertsch — COMMENTED** [review]
Thanks for the update!
For the examplesURL you are encouraged to provide a link to a webpage or repo where you document how you tested your tool w.r.t to FMI support. See e.g. [https://github.com/altairengineering/fmus](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faltairengineering%2Ffmus&data=05%7C01%7CChristian.Bertsch%40de.bosch.com%7C01cb7050c3044b3d2c2e08dbd1ac4020%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C638334309952318885%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7cblzvmoxG496WskCZUVcxnJzQU8aDUxkUDtydXdl2A%3D&reserved=0) for an example

**Comment by ThummeTo** [comment]
Ah, I see!
Can you please wait with merging? So I can add the new fields too.

**Comment by ThummeTo** [comment]
Added `examplesUrl` and `interfaces` 👍

**Review by chrbertsch — CHANGES_REQUESTED** [review]
Could you please for the examplesUrl provide a link to a page where you describe how you have tested FMI import and export, see https://github.com/modelica/fmi-standard.org/blob/main/CONTRIBUTING.md#updating-the-tools-list or one of the first four tools listed on https://fmi-standard.org/tools/ as an example
(The provided example FMUs are great, but for users it is important to know, with which other tools you have tested the import export)
Thanks!

**Comment by ThummeTo** [comment]
I'm on it!

**Comment by t-sommer** [comment]
> Ah, I see! Can you please wait with merging? So I can add the new fields too.

You can open a new PR any time.

**Pull request merged**
