### PR TITLE
Add Industrial user presentations

### PR DESCRIPTION
**Pull request by chrbertsch**
(agreed on by presenters)

### CODE REVIEW

**Comment by t-sommer** [comment]
Shouldn't go this into https://modelica.org/events/modelica2019/subpages/modelica-conference-2019-proceedings ?

**Comment by chrbertsch** [comment]
To my information, MA does not publish slides in their proceedings.
In the past we uploaded the PDF-Slides (if the presenters agreed) to SVN and linked them in https://fmi-standard.org/literature/ (addtionally to the papers from the proceedings)

**Comment by sjoelund** [comment]
The proceedings is the scientific track, with DOI identifiers and such. I do think they should be published on the 2019 conference site, but not the proceedings.

I will move the old webpage to a github page similar to https://2017.international.conference.modelica.org/ in the future, so make some suggestions where to put it in such a layout.

**Comment by chrbertsch** [comment]
@sjoelund : this is fine for me. One could create an entry point for the "Industrial User Presentations" within the "Conference Program" https://2017.international.conference.modelica.org/ and/or  "further material" just like here:  https://2017.international.conference.modelica.org/proceedings/html/material.html

**Comment by t-sommer** [comment]
@chrbertsch, can we close this PR and open a new one when the Modelica 2019 repo is set up?

**Comment by chrbertsch** [comment]
@sjoelund  What about https://github.com/modelica/ModelicaConference2019/IndustrialUserPresentations ? 
(by the way: Shouldn't one provide a similar possibility for vendor sessions and tutorial material?)

**Comment by chrbertsch** [comment]
I think it would be good to provide the slides soon. As the slides have not been included on the conferecen page, I suggest to proceed with this PR. Then I will update the literature page. Once the slides are on the Conferecen archive I will update the links and remove the slides from the assets folder

**Comment by t-sommer** [comment]
@chrbertsch, the files are fairly large and will remain in the history of the repo. Can't we just put them in a separate repo as suggested above?

**Comment by chrbertsch** [comment]
@sjoelund : Could you please point me to where I should commit the slides from the Industrial User meeting?
Or shall I upload them to the old FMI SVN?

**Comment by chrbertsch** [comment]
I have uploaded the files to https://svn.fmi-standard.org/fmi/branches/public/docs/Modelica2019/Industrial_User_Presentations_Modelica2019/ 
@sjoelund : once you provide me with a link where to upload the slides on the "conserved conference page" https://github.com/modelica/ModelicaConference2019/ we can move them there.

**Pull request closed without merging**
