### PR TITLE
Updating ETAS tool-list

### PR DESCRIPTION
**Pull request by Hela-Guesmi**
Updating ETAS tool-list.
One tool is removed and the information related to the other tools have been updated

### CODE REVIEW

**Comment by chrbertsch** [comment]
@Hela-Guesmi : What about SCODE-CONGRA? It also can export FMUs. (Please check with Markus Behle). Thanks.

**Comment by Hela-Guesmi** [comment]
@chrbertsch I will check with him

**Comment by Hela-Guesmi** [comment]
@chrbertsch I have just added the tool

**Comment by chrbertsch** [comment]
@Hela-Guesmi : the link to COSYM does not work correctly.

**Pull request merged**
