### PR TITLE
Add FMU Manipulation Toolbox to the tools list

### PR DESCRIPTION
**Pull request by nl78**

### CODE REVIEW

**Review by chrbertsch — COMMENTED** [review]
Thanks for the pull request!
Regarding the page https://github.com/grouperenault/fmutool/tree/main/doc that you link from "ExamplesURL":
Could you please add information, with which FMUs from which exporting tools you have tested fmutool? (including the References FMUs?)
And with which tools and checkers from https://fmi-standard.org/validation/ you tested the re-exported FMUs?

**Comment by nl78** [comment]
I just added https://github.com/grouperenault/fmutool/tree/main/doc#readme
Current (public) automated tests suite includes only 1 FMU.

**Review by t-sommer — CHANGES_REQUESTED** [review]
IMHO the name "fmutool" conflicts with the [trademark usage guidelines of the FMI](https://fmi-standard.org/about/):

> The use of the letters FMI or FMU in a product name, reference or other relevant context is not allowed when:
> [...]
> The use can be interpreted as a variant, subset or improvement of the original FMI standard (e.g. using a tool name, say FMIplus, that can be interpreted as supporting with extensions/improvements with respect to one of the FMI versions),

**Comment by nl78** [comment]
Could the name "fmutool" lead someone to believe it is a variant of the FMI standard?
Changing the name at this stage would be difficult (it is use internally at Renault and publicly released). What alternatives?

**Comment by t-sommer** [comment]
Maybe something like "Renault FMU Tool"?

**Comment by chrbertsch** [comment]
> Renaming will involve some rework. Before proceeding, I would like to ensure that the new name is acceptable : we selected 2 candidates : "FMU Python Toolbox" or "FMU Manipulation Toolbox". Do they meet FMI Guidelines ?

Thanks, both suggestions are fine for us. 
(I personally think that second is more descriptive for what your tool does)

**Comment by nl78** [comment]
I proceeded to the renaming and rebase on last commit. Please, let me know if any issue left.

**Review by chrbertsch — APPROVED** [review]
Thanks for the renaming

**Review by t-sommer — APPROVED** [review]

**Pull request merged**
