### PR TITLE
Add FMIExchange.jl to tools

### PR DESCRIPTION
**Pull request by CasBex**
Add [FMIExchange.jl](https://github.com/Electa-Git/FMIExchange.jl) to the tools list. See also https://github.com/Electa-Git/FMIExchange.jl/issues/4 .

### CODE REVIEW

**Review by chrbertsch — COMMENTED** [review]
Thanks for your Pull Request. 
Could you please describe on the webpage linked by examplesURL, with which FMUs from which exporting tools you have tested your tool?
We recommend to include the Reference FMUs here, too. https://github.com/modelica/Reference-FMUs/releases

**Comment by CasBex** [comment]
The new examples URL points to the homepage of FMIExchange.jl's documentation. In the Reproducibility-section at the bottom of the page, the FMU compilation tool is listed and is updated automatically if the documentation updates.

I don't plan on testing the reference FMUs in FMIExchange.jl since it relies on another library (FMIImport.jl) to load and handle the FMUs. FMIExchange.jl is solely a compatibility layer between two packages, so testing the reference FMUs has limited value.

**Comment by chrbertsch** [comment]
> The new examples URL points to the homepage of FMIExchange.jl's documentation. In the Reproducibility-section at the bottom of the page, the FMU compilation tool is listed and is updated automatically if the documentation updates.
> 
> I don't plan on testing the reference FMUs in FMIExchange.jl since it relies on another library (FMIImport.jl) to load and handle the FMUs. FMIExchange.jl is solely a compatibility layer between two packages, so testing the reference FMUs has limited value.

Thanks for the clarification.
Could you perhaps under the a header "Compatibility information" write, that you tested your tool for a list of example FMUs generated  with OpenModelica ?

**Comment by CasBex** [comment]
> Thanks for the clarification. Could you perhaps under the a header "Compatibility information" write, that you tested your tool for a list of example FMUs generated with OpenModelica ?

You mean, an extra header "Compatibility Information" in the FMIExchange.jl documentation at https://electa-git.github.io/FMIExchange.jl/dev/ or in the README?

**Comment by chrbertsch** [comment]
> > Thanks for the clarification. Could you perhaps under the a header "Compatibility information" write, that you tested your tool for a list of example FMUs generated with OpenModelica ?
> 
> You mean, an extra header "Compatibility Information" in the FMIExchange.jl documentation at https://electa-git.github.io/FMIExchange.jl/dev/ or in the README?

In https://electa-git.github.io/FMIExchange.jl/dev/, if your examplesURL links to there. 

It would be also very valuable in the "Compatibiltiy information" that your tool uses  FMIImport.jl and thus has the same compatibility for the import of FMUs as this package. (see https://github.com/ThummeTo/FMI.jl/issues/220)

**Comment by CasBex** [comment]
Alright. Just to avoid excessive PRs on the FMIExchange.jl repo, can you confirm that attachment suffices for the Examples & Compatibility page. (open index.html with a web browser)
[build.zip](https://github.com/modelica/fmi-standard.org/files/15221674/build.zip)

**Comment by CasBex** [comment]
The documentation should be online in 15 minutes or so

**Review by chrbertsch — APPROVED** [review]

**Comment by CasBex** [comment]
@chrbertsch I have no write permissions so could you please merge?

**Pull request merged**
