### PR TITLE
Create 2018-10-23-fmi-design-meeting

### PR DESCRIPTION
**Pull request by chrbertsch**
New news entry for fmi-design meeting

### CODE REVIEW

**Comment by andreas-junghanns** [comment]
I accepted the PR, but somehow the rendered page does not pick it up - Torsten, any idea?

**Comment by t-sommer** [comment]
The date in the file name must not be in the future. It's supposed to be the date of the announcement (not the date of the event).

**Comment by chrbertsch** [comment]
But it is the same with https://github.com/modelica/fmi-standard.org/blob/master/_posts/2018-10-09-FMI-ModelicaConferenceAmericas.markdown. Why does this work?

**Comment by t-sommer** [comment]
The file you've added is missing the `.md` file extension. If fixed this in [PR 41](https://github.com/modelica/fmi-standard.org/pull/41).

**Comment by chrbertsch** [comment]
Hi Torsten, I cannot find it in the modified files of the PR. Best, Christian

**Comment by t-sommer** [comment]
I forgot to push 😬

**Pull request merged**
