### PR TITLE
Update of tools.json to add Persalys

### PR DESCRIPTION
**Pull request by angmarion**
Updated the description of Persalys in tools.json

### CODE REVIEW

**Comment by angmarion** [comment]
Hi Torsten,

I also have a new logo to add in static/assets/images/logos but cannot upload it.
Here it is:
Persalys

Would it be possible to add it too?

**Comment by chrbertsch** [comment]
Hello @angmarion , have you closed this pull request intentionally?
(Uploading the the logo seems to be blocked by settings in your fork)

**Comment by angmarion** [comment]
Hello Christian,
My bad, I must have closed it out of habit. I reopened it now.

**Comment by t-sommer** [comment]
You have to allow commits by maintainers if you want us to fix it.

**Comment by angmarion** [comment]
I have already checked the "Allow edits by maintainers" option. Is there another option?

**Pull request merged**
