### PR TITLE
Add WRP to tools page

### PR DESCRIPTION
**Pull request by WinRingTech**
Hello, here are two FMI related tools of our company, please check.

thanks!

### CODE REVIEW

**Review by chrbertsch — APPROVED** [review]
Looks good, Thanks!
It would be great if you could provide provide compatibility information (see https://github.com/modelica/fmi-standard.org/blob/main/CONTRIBUTING.md#compatibility-information), i.e. how you tested your FMI implementation? (Could also be in a separate Pull Request.) Benefit: your tool will get the "yellow star" and be listed on the top.

**Comment by WinRingTech** [comment]
> Looks good, Thanks! It would be great if you could provide provide compatibility information (see https://github.com/modelica/fmi-standard.org/blob/main/CONTRIBUTING.md#compatibility-information), i.e. how you tested your FMI implementation? (Could also be in a separate Pull Request.) Benefit: your tool will get the "yellow star" and be listed on the top.

ok, we will check it, when we get ready, we will commit a new PR.
thanks!

**Comment by chrbertsch** [comment]
@WinRingTech  and @t-sommer :  the logo is very small.  Can we improve this?
[WRP-SimConductor](http://www.winring.com.cn/page-product01.html)

**Comment by t-sommer** [comment]
Fixed with 689d9246f42b77eb03b47f97750c3d29ee859c2d.

**Pull request merged**
