### PR TITLE
Add PySimulator to list of tools

### PR DESCRIPTION
**Pull request by beutlich**
See https://github.com/PySimulator/PySimulator/issues/71

### CODE REVIEW

**Comment by chrbertsch** [comment]
@beutlich : you are one of the developers of PySimulator, right?
I appreciate adding PySimulator to the list.

**Comment by beutlich** [comment]
Yes, I contributed to PySimulator, which is mainted by DLR, but development is suspended.

**Comment by t-sommer** [comment]
@beutlich, please fix the conflicts or enable commits by maintainers

**Comment by beutlich** [comment]
This is default.
grafik

**Comment by t-sommer** [comment]
Strange... I couldn't push :-(

**Comment by beutlich** [comment]
Means, you aren't a maintainer then.

**Comment by beutlich** [comment]
Updated PR

**Comment by t-sommer** [comment]
Too late ;-)

**Comment by beutlich** [comment]
That is considered bad style.

**Pull request closed without merging**
