### PR TITLE
Update tools.json by adding Simulink Real-time to the supported tool list

### PR DESCRIPTION
**Pull request by liweiwu**
Add Simulink Real-time to the supported tool list.  Thanks.

### CODE REVIEW

**Review by chrbertsch — APPROVED** [review]
We would like to encourage you to provide "Compatibility information" described how you tested your FMI import and export, see https://github.com/modelica/fmi-standard.org/blob/main/CONTRIBUTING.md#updating-the-tools-list or one of the first four tools listed on https://fmi-standard.org/tools/ as an example. This can be provided in a separate pull request.

**Comment by t-sommer** [comment]
"... MATLAB and Simulink" in the description is missing the ® symbol. Is this intentional?

**Comment by liweiwu** [comment]
> "... MATLAB and Simulink" in the description is missing the ® symbol. Is this intentional?

Thanks for catching this Torsten.  yes, it would be nice to keep them consistent. Could you help add these at your end or do I need to submit a new request?

**Comment by liweiwu** [comment]
I made the updates.

**Pull request merged**
