### PR TITLE
Add Easy FMI Add-on to the tool list

### PR DESCRIPTION
**Pull request by jcornau**

### CODE REVIEW

**Comment by chrbertsch** [comment]
@jcornau: could you please fix the two error that caused the check to fail?
> 2 problems found in _data/tools.csv
()
tool_name 'Easy FMI Add-on for Matlab/Simulink' is not in alphabetical order
()
Easy_FMI_Add_on: Capabilities must be planned, available or empty

**Comment by t-sommer** [comment]
@jcornau, please have a look at the failed checks and fix your PR

**Comment by jcornau** [comment]
Hi Torsten,

Yes I got the notification. I will handle that as soon as possible (I am in travel for the current days).

Best regards,
Jerome Cornau

De : Torsten Sommer <notifications@github.com>
Envoyé : mercredi 13 mars 2019 14:15
À : modelica/fmi-standard.org <fmi-standard.org@noreply.github.com>
Cc : Jerome Cornau <j.cornau@powersys.fr>; Mention <mention@noreply.github.com>
Objet : Re: [modelica/fmi-standard.org] Add Easy FMI Add-on to the tool list (#129)


@jcornau<https://github.com/jcornau>, please have a look at the failed checks and fix your PR

**Comment by jcornau** [comment]
I did not find how to fix the issues here. I did them in Add Easy FMI add on to the list. Let me know if I have to do anything. Sorry for the inconvenience.

**Comment by t-sommer** [comment]
Your last commit passed the check successfully. Do you still want to merge it?

**Comment by jcornau** [comment]
Yes if possible.

Jerome

De : Torsten Sommer <notifications@github.com>
Envoyé : mercredi 10 avril 2019 15:20
À : modelica/fmi-standard.org <fmi-standard.org@noreply.github.com>
Cc : Jerome Cornau <j.cornau@powersys.fr>; State change <state_change@noreply.github.com>
Objet : Re: [modelica/fmi-standard.org] Add Easy FMI Add-on to the tool list (#129)


Your last commit passed the check successfully. Do you still want to merge it?

**Comment by jcornau** [comment]
Torsten,

I just found a mistake (available is on version 1 instead of version 2). Is it possible to modify it or I need to recreate a branch and do the process ?

Regards,
Jerome

De : Torsten Sommer <notifications@github.com>
Envoyé : mercredi 10 avril 2019 16:40
À : modelica/fmi-standard.org <fmi-standard.org@noreply.github.com>
Cc : Jerome Cornau <j.cornau@powersys.fr>; State change <state_change@noreply.github.com>
Objet : Re: [modelica/fmi-standard.org] Add Easy FMI Add-on to the tool list (#129)


Merged #129<https://github.com/modelica/fmi-standard.org/pull/129> into master.

**Comment by t-sommer** [comment]
Please make a new PR

**Pull request merged**
