### PR TITLE
Remove discontinued Modelon tools from tools.csv

### PR DESCRIPTION
**Pull request by t-sommer**
According to https://www.modelon.com/products-services/modelon-deployment-suite/ the "FMI Composer" and "FMI Add-in for Excel" are no longer available.

### CODE REVIEW

**Comment by chrbertsch** [comment]
@hubertus65: Could you please comment?
This would also mean disappearnce from the XC tables, right?
But the tools might be still in usage, right?

**Comment by hubertus65** [comment]
That is correct, fine to merge to trunk. @chrbertsch: the tools are still in usage, that is correct, and probably will for some time to come. From that point of view it could be better to mark them in a different way.

**Comment by t-sommer** [comment]
> From that point of view it could be better to mark them in a different way.

...like a "discontinued" column?

**Comment by chrbertsch** [comment]
As this is a special case (a commercial tool to be listed that is no longer available for sale): we could put a "(discontinued)" into the tool name, i.e. "FMU Composer (discontinued)"

**Comment by andreas-junghanns** [comment]
> 
> 
> As this is a special case (a commercial tool to be listed that is no longer available for sale): we could put a "(discontinued)" into the tool name, i.e. "FMU Composer (discontinued)"

I like this proposal, this is easier than adding a new column. At least until this happens more often...

**Comment by andreas-junghanns** [comment]
Can we agree like this?

**Comment by chrbertsch** [comment]
> 
> 
> Can we agree like this?

fine for me

**Comment by andreas-junghanns** [comment]
Torsten is planning a different fix.

**Pull request closed without merging**
